export const CrSignalNames = {
    //App
    'programStart': '29',
    
    //Welcome Page
    'startJoin' : '1',

    //Source Menus
    'ShowDesktop': '211',
    'ShowLaptop': '212',
    'ShowWireless': '213',
    'ShowBluray': '214',
    'ShowDocCam': '215',
    'ShowConfCall': '217',
    'Source_Display1': '51',
    'Source_Display2': '52',
    'HasDisplay2': '36',
    'Source_Desktop_Display1': '200',
    'Source_Laptop_Display1': '201',
    'Source_Wireless_Display1': '202',
    'Source_ConfCall_Display1': '205',
    'Source_DocCam_Display1': '204',
    'Source_Bluray_Display1': '203',
    'Source_Desktop_Display2': '430',
    'Source_Laptop_Display2': '431',
    'Source_Wireless_Display2': '432',
    'Source_ConfCall_Display2': '435',
    'Source_DocCam_Display2': '434',
    'Source_Bluray_Display2': '433',
    'Mute_Display1': '253',
    'ShowAnnotation_Display1': '42',
    'ShowFullScreen_Display1': '44',
    'HandleAnnotation_Display1': '41',
    'HandleFullScreen_Display1': '43',
    'PowerOff_Display1': '251',
    'PowerOn_Display1': '252',
    'Screen_Up_Display1': '256',
    'Screen_Down_Display1': '255',
    'ShowDisplayModal_Display1': '8',
    'CloseDisplayModal_Display1': '39',
    'IsElectricScreen_Display1': '257',
    'Is_Projector_Display1': '32',
    'Mute_Display2': '260',
    'ShowAnnotation_Display2': '46',
    'ShowFullScreen_Display2': '48',
    'HandleAnnotation_Display2': '45',
    'HandleFullScreen_Display2': '47',
    'PowerOff_Display2': '258',
    'PowerOn_Display2': '259',
    'Screen_Up_Display2': '263',
    'Screen_Down_Display2': '262',
    'ShowDisplayModal_Display2': '37',
    'CloseDisplayModal_Display2': '38',
    'IsElectricScreen_Display2': '264',
    'Is_Projector_Display2': '33',

    //Bottom Bar
    'PresentationVolume': '1',
    'MicVolume': '2',
    'NumberOfCameras': '41',
    'NumberOfPresets': '46',
    'CameraSelected': '42',
    'PresetSelected': '47',
    'PresentationMuted': '20',
    'MicMuted': '23',
    'CeilingMicMuted': '111',
    'HasCeilingMics': '112',
    'HasMics': '9',
    'ShowVolumeModal': '95',
    'ShowPowerModal': '6',
    'ShowMicModal': '97',
    'ShowCamModal': '88',
    'ConfigPrivacyMode': '79',
    'IsPrivacyModeEnabled': '103',
    'PresetNameBaseIdx': 101,
    'CameraNameBaseIdx': 91,
    'PowerOff': '30',
    'HandleShowPowerModal': '5',
    'ClosePowerModal': '31',
    'CloseVolumeModal': '96',
    'CloseMicModal': '98',
    'CloseCamModal': '89',
    'PresetLongPress': '48',
    'CameraLongPress': '43',
    'SaveNewNameAnalog': '40',
    'SaveNewNameDigital': '190',
    'PresentationVolumeUp': '22',
    'PresentationVolumeDown': '21',
    'MicVolumeUp': '25',
    'MicVolumeDown': '24',
    'Camera_Up': '241',
    'Camera_Down': '242',
    'Camera_Left': '243',
    'Camera_Right': '244',

    //Display Area
    'IpAddress': '2',
    'ShowConfCallModal': '117',
    'CloseConfCallModal': '118',
    'ConfCall_DialString': '16',
    'ConfCall_Volume': '3',
    'ConfCall_Mute': '100',
    'ShowConfCallIncomingCall': '109',
    'ConfCall_EndCall': '105',
    'ConfCall_CallActive': '106',
    'Config_PrivacyMode': '79',
    'EnablePrivacyMode': '103',
    'ShowBlurayModal': '55',
    'CloseBlurayModal': '56',
    'DocCam_LampOn': '85',
    'DocCam_LampOff': '86',
    'DocCam_AutoFocus': '80',
    'ConfCall_DialPad_1': '281',
    'ConfCall_DialPad_2': '282',
    'ConfCall_DialPad_3': '283',
    'ConfCall_DialPad_4': '284',
    'ConfCall_DialPad_5': '285',
    'ConfCall_DialPad_6': '286',
    'ConfCall_DialPad_7': '287',
    'ConfCall_DialPad_8': '288',
    'ConfCall_DialPad_9': '289',
    'ConfCall_DialPad_0': '290',
    'ConfCall_DialPad_Star': '291',
    'ConfCall_DialPad_Pound': '292',
    'ConfCall_DialString_Clear': '104',
    'ConfCall_DialString_Backspace': '107',
    'ConfCall_CallIgnore': '108',
    'ConfCall_VolumeUp': '102',
    'ConfCall_VolumeDown': '102',
    'DocCam_ZoomOut': '83',
    'DocCam_ZoomIn': '84',
    'Bluray_Up': '271',
    'Bluray_Right': '272',
    'Bluray_Down': '273',
    'Bluray_Left': '274',
    'Bluray_Ok': '275',
    'Bluray_Previous': '57',
    'Bluray_Next': '58',
    'Bluray_Eject': '59',
    'Bluray_Home': '60',
    'Bluray_Info': '61',
    'Bluray_Menu': '62',
    'Bluray_Return': '63',
    'Bluray_Play': '64',
    'Bluray_Pause': '65',
    'Bluray_Stop': '66',
    'Bluray_Rewind': '67',
    'Bluray_Fast_Forward': '68',

    //Header
    'RoomName': '1',
    'IpAdd' : '2',
    'ConfigRoomName': '5',
    'ConfigIpAdd': '6',
    'ShowPasswordModal': '121',
    'ShowAdminModal' : '93',
    'PwInputValue': '25',
    'NumberOfTextFields' : '22',
    'NumberOfToggleButtons': '21',
    'TextFieldsBaseIdx' : 71,
    'TextFieldsValuesBaseIdx' : 23,
    'ToggleButtonsStatesBaseIdx' : 331,
    'ToggleButtonsBaseIdx' : 51,
    'ShowHelpModal' : '150',
    'CloseHelpModal' : '151',
    'HandleShowAdminModal' : '130',
    'CloseAdminModal' : '123',
    'ClosePasswordModal' : '122',
    'HandleShowPasswordModal' : '120',
    'PW_1' : '131',
    'PW_2' : '132',
    'PW_3' : '133',
    'PW_4' : '134',
    'PW_5' : '135',
    'PW_6' : '136',
    'PW_7' : '137',
    'PW_8' : '138',
    'PW_9' : '139',
    'PW_0' : '140',
    'SaveConfigFile' : '124',
    'ResetConfigFile' : '125',
    'PwBackSpace' : '129',
    'TextFieldsValuesIncDecBaseIdx' : 361
  }

export const CrSignalType = {
'Boolean' : 'b',
'Number' : 'n',
'String': 's',
}